### ISSUE TITLE
Docker Swarm setup 

### ISSUE THREAD

**Issue by nagy1991** [klausbetz/apple-identity-provider-keycloak#70]
Hi, could you help me with how I can install the apple addition on the docker swarm platform.A stack files would come. Thanks

`
version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trnet

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start --http-port=8180
    environment:
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: keycloak.test.hu
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_PASSWORD: 123456
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=trnet"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.test.hu`)"
      - "traefik.http.routers.keycloak.entrypoints=http"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8180"
      - "traefik.http.routers.keycloak.middlewares=force-https-traefik"
      - "traefik.http.middlewares.force-https-traefik.redirectscheme.scheme=https"
      - "traefik.http.routers.keycloak_https.rule=Host(`keycloak.test.hu`)"
      - "traefik.http.routers.keycloak_https.entrypoints=https"
      - "traefik.http.routers.keycloak_https.tls.certresolver=letsencrypt"
    networks:
      - trnet

volumes:
  postgres_data:
    driver: local
  keycloak_data:

networks:
   trnet:
     external: true
`

**Comment by klausbetz** [comment]
Hi @nagy1991,
to be honest, I'm not familiar with Docker Swarm.

Anyways, to install the Apple extension in the docker container you just have to mount the JAR into the Keycloak container.
See this example:

```yml
version: "3"
services:
  keycloak:
    container_name: keycloak_test
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      ...
    volumes:
      - /path/to/apple-identity-provider.jar:/opt/keycloak/providers/apple.jar
    
  ...
```
